models/ChangeLog.php
<?php

namespace app\models;

use app\utils\Common;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;

/**
 * This is the model class for table "change_log".
 *
 * @property string $id
 * @property string $create_time 发生时间
 * @property string $user_id 操作员ID
 * @property string $user_full_name 操作员
 * @property string $table 表格
 * @property string $reference_id 相关记录ID
 * @property int $action 操作
 * @property string $old 备份
 *
 * @property User $user
 */
class ChangeLog extends \app\utils\CommonActiveRecord
{
	public static function tableLabel()
    {
        return '更新日志';
    }
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'change_log';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['user_id', 'user_full_name', 'table', 'reference_id', 'action'], 'required'],
            [['user_id', 'reference_id', 'action'], 'integer'],
            [['old'], 'string'],
            [['user_full_name', 'table'], 'string', 'max' => 50],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'create_time' => '发生时间',
            'user_id' => '操作员ID',
            'user_full_name' => '操作员',
            'table' => '表格',
            'reference_id' => '相关记录ID',
            'action' => '操作',
            'old' => '备份',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

	const ACTION_INSERTED = '新增',
        ACTION_UPDATED = '更新',
        ACTION_DELETED = '删除';

    /**
     * @param $action
     * @return int
     */
    public static function getActionId($action){
        return array_search($action, self::getAllActions());
    }
    public static function getActionTextFor($actionId){
        return ArrayHelper::getValue(self::getAllActions(), $actionId);
    }
    public static function getAllActions(){
        return [
            self::ACTION_INSERTED,
            self::ACTION_UPDATED,
            self::ACTION_DELETED,
        ];
    }
	
	public function getActionText() {
		return self::getActionTextFor($this->action);
	}

    public static function inserted($tableName, $id)
    {
        self::modified($tableName, $id, null, self::ACTION_INSERTED);
    }

    public static function updated($tableName, $id, $changedAttributes)
    {
        self::modified($tableName, $id, $changedAttributes, self::ACTION_UPDATED);
    }

    public static function deleted($tableName, $id, $attributes)
    {
        self::modified($tableName, $id, $attributes, self::ACTION_DELETED);
    }

    public static function modified($tableName, $refId, $attributes, $action){
        $log = new ChangeLog();
        $log->create_time = Common::now();
        $log->table = $tableName;
        $log->reference_id = $refId;
        $log->action = self::getActionId($action);
        if (!empty($attributes)) {
			$log->old = Json::encode($attributes);
		}
		if(!$log->save()){
            \Yii::error(self::tableName() . " 未保存 \n" . Json::encode($log) . "\n" . Json::encode($log->getErrorSummary(true)), self::className() . '.' . $action);
        }
    }
	/**
	 * referenced model with changed backup value ($old as attribute values)
	 * @return \app\utils\CommonActiveRecord
	 */
	public function getReferencedModel() {
		if($model = self::getModelFor($this->table)){
			$model->setAttributes(\yii\helpers\Json::decode($this->old));
		}
		return $model;
	}

	public static function getHistoryFor($table, $reference_id, &$modelNow) {
		if($modelNow = ChangeLog::getModelFor($table)){
			$modelNow = $modelNow::findOne($reference_id);
		}
		$class = ChangeLog::getClassFor($table);
		$changeLogs = ChangeLog::find()->where([
			'table' => $table,
			'reference_id' => $reference_id
		])->orderBy('create_time desc')->all();
		//latest state is the $modelNow
		$model = new $class;
		$model->setAttributes($modelNow->getAttributes());
		$history = [
			0 => ['model' => $model]
		];
		foreach ($changeLogs as $i => $changeLog){
			//operator and time
			$history[$i]['changeLog'] = $changeLog;
			//state
			if($i > 0){
				self::setBasedOnPreviousModel($history, $changeLogs, $i, $class);
			}
		}
		//set initial insert history
		$i = count($changeLogs);
		
		$history[$i]['changeLog'] = self::getChangeLogFromModel($modelNow);
		if(count($changeLogs) == 0){
			//return "无更新历史记录";
			//model was already set before loop
		}else{
			self::setBasedOnPreviousModel($history, $changeLogs, $i, $class);
		}
		return array_reverse($history);
	}

	private static function setBasedOnPreviousModel(&$history, $changeLogs, $i, $class) {
		$model = new $class;
		//based on previous state
		$model->setAttributes($history[$i - 1]['model']->getAttributes());
		//changeLog->old is the previous state, so shift
		$model->setAttributes(Json::decode($changeLogs[$i - 1]->old));
		$history[$i]['model'] = $model;
	}

	public static function getChangeLogFromModel($modelNow) {
		$changeLog = new ChangeLog();
		$changeLog->setAttributes($modelNow->getAttributes(['create_time', 'user_id', 'user_full_name']));
		$changeLog->create_time = $modelNow->create_time;
		$changeLog->action = self::getActionId(self::ACTION_INSERTED);
		return $changeLog;
	}

}

controllers/ChangeLogController.php
<?php

namespace app\controllers;

use app\models\User;
use Yii;
use app\models\ChangeLog;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\Json;

/**
 * ChangeLogController implements the CRUD actions for ChangeLog model.
 */
class ChangeLogController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function beforeAction($action)
    {
        if(parent::beforeAction($action)){
            $this->getView()->params['activeUrl'] = ['/change-log'];
            return true;
        }
        return false;
    }

    /**
     * Lists all ChangeLog models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => ChangeLog::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single ChangeLog model.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }
	
	public function actionHistory($table, $reference_id) {
		$this->layout = 'basic';
		$modelNow = null;
		$history = ChangeLog::getHistoryFor($table, $reference_id, $modelNow);
		return $this->render('history', [
			'modelNow' => $modelNow,
			'history' => $history
		]);
	}

    /**
     * Creates a new ChangeLog model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new ChangeLog();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing ChangeLog model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing ChangeLog model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        //TODO with caution
        //$this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the ChangeLog model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return ChangeLog the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = ChangeLog::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('记录未找到');
    }
}

controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use app\models\User;
use yii\base\Exception;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\helpers\Json;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\HttpException;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function beforeAction($action)
    {
        if(parent::beforeAction($action)){
            $this->getView()->params['activeUrl'] = ['/user'];
            return true;
        }
        return false;
    }

    /**
     * Lists all User models.
     * @return mixed
     * @throws \Throwable
     */
    public function actionIndex()
    {
        $user = Yii::$app->user->getIdentity();
        //if not manager or admin, go to update self info
        if($user->role < User::ROLE_MANAGER){
            return $this->redirect(['view', 'id' => $user->id]);
        }
        $dataProvider = new ActiveDataProvider([
            'query' => User::whereForRole(Yii::$app->user->getIdentity()->role),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     * @throws HttpException
     * @throws \Throwable
     */
    public function actionCreate()
    {
        if(!Yii::$app->user->getIdentity()->hasCreateAccess()) throw new HttpException(403);
        $model = new User();

        if (Yii::$app->request->isPost) {
            $tx = Yii::$app->db->beginTransaction();
            try {
                $this->handleNewUser($model);
                $result = [
                    'ok' => true,
                    'redirect' => Url::to(['view', 'id' => $model->id]),
                ];
                $tx->commit();
            } catch (Exception $e) {
                $tx->rollBack();
                Yii::error($e->getMessage(), 'UserController.actionCreate');
                $result = [
                    'ok' => false,
                    'message' => $e->getMessage(),
                ];
            }
            return Json::encode($result);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
//        $model->forUpdate();

        if (Yii::$app->request->isPost) {
            $tx = Yii::$app->db->beginTransaction();
            try {
                $this->handleUpdateUser($model);
                $result = [
                    'ok' => true,
                    'redirect' => Url::to(['view', 'id' => $model->id]),
                ];
                $tx->commit();
            } catch (Exception $e) {
                $tx->rollBack();
                Yii::error($e->getMessage(), 'UserController.actionUpdate');
                $result = [
                    'ok' => false,
                    'message' => $e->getMessage(),
                ];
            }
            return Json::encode($result);
        }

        $model->password = null;
        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        //$this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findWhereValid()->andWhere(['id' => $id])->one()) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('未找到Model');
    }

    private function handleNewUser(User $model)
    {
        $model->load(Yii::$app->request->post());
        $model->newUser();
        $model->trySave();
    }

    private function handleUpdateUser(User $model)
    {
        $model->load(Yii::$app->request->post());
        $model->updateUser();
        $model->trySave();
    }
}

views/change-log/history.php
<?php

use app\utils\CommonView;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $history array [[changeLog, model]] */
/* @var $modelNow app\utils\CommonActiveRecord */

if(!$modelNow) return;
$this->title = $modelNow::tableLabel() . '#' . $modelNow->id . ' 更新历史';
$this->params['breadcrumbs'][] = ['label' => $modelNow::tableLabel(), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
$attributeNames = array_keys($modelNow->getAttributes(null, ['id', 'create_time', 'user_id', 'user_full_name', 'auth_key']));
?>
<div class="change-log-view">

    <div class="page-header">
        <h1>
			<?= yii\helpers\Html::a('&lt;', ['index'], ['class' => 'btn btn-default pull-left']) ?>
            <?= $this->title ?>
        </h1>
    </div>

    <table class="table table-striped table-bordered">
		<tr>
			<td>
				<?= $history[0]['changeLog']->getAttributeLabel('create_time') ?>
			</td>
			<td>
				<?= $history[0]['changeLog']->getAttributeLabel('action') ?>
			</td>
			<td>
				<?= $history[0]['changeLog']->getAttributeLabel('user_id') ?>
			</td>
			<td>
				<?= $history[0]['changeLog']->getAttributeLabel('user_full_name') ?>
			</td>
			<?php foreach($attributeNames as $attr){ ?>
			<td>
				<?= $modelNow->getAttributeLabel($attr) ?>
			</td>
			<?php } ?>
		</tr>
		<?php foreach($history as $i => $hist){ ?>
		<tr>
			<td>
				<?= $history[$i]['changeLog']->create_time ?>
			</td>
			<td>
				<?= $history[$i]['changeLog']->getActionText() ?>
			</td>
			<td>
				<?= $history[$i]['changeLog']->user_id ?>
			</td>
			<td>
				<?= $history[$i]['changeLog']->user_full_name ?>
			</td>
			<?php foreach($attributeNames as $attr){ ?>
			<td>
				<?= $history[$i]['model']->textValue($attr) ?>
			</td>
			<?php } ?>
		</tr>
		<?php } ?>
    </table>

</div>

views/change-log/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$model = new app\models\ChangeLog();
$this->title = $model::tableLabel();
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="change-log-index">

    <div class="page-header">
        <h1><?= $this->title ?></h1>
    </div>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'create_time',
			'user_id',
			'user_full_name',
            [
                'attribute' => 'table',
                'label'=> $model->getAttributeLabel('table'),
                'value' => function ($model, $key, $index, $column){
					$ref = $model->getReferencedModel();
                    return $ref ? $ref::tableLabel() : $model->table;
                }
            ],
			'reference_id',
            [
                'attribute' => 'action',
                'label'=> $model->getAttributeLabel('action'),
                'value' => function ($model, $key, $index, $column){
                    return $model->getActionText();
                }
            ],

            'old:ntext',

            ['class' => 'yii\grid\ActionColumn', 'template' => '{view}'],
        ],
    ]); ?>


</div>

views/change-log/view.php
<?php

use app\utils\CommonView;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\models\ChangeLog */

$this->title = $model::tableLabel();
$this->params['breadcrumbs'][] = ['label' => $model->tableLabel(), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
$ref = $model->getReferencedModel();
?>
<div class="change-log-view">

    <div class="page-header">
        <h1>
            <?= $this->title ?>
        </h1>
    </div>

    <table class="table table-striped table-bordered">
        <tr>
            <td>
                <?= $model->getAttributeLabel('id') ?>
            </td>
            <td class="text-info" onclick="$('.time').toggleClass('hidden')">
                <?= $model->getAttribute('id') ?>
            </td>
        </tr>
        <tr class="time">
            <td>
                <?= $model->getAttributeLabel('create_time') ?>
            </td>
            <td class="text-info">
                <?= $model->getAttribute('create_time') ?>
            </td>
        </tr>
        <tr>
            <td>
                <?= $model->getAttributeLabel('user_id') ?>
            </td>
            <td class="text-info">
                <a class="link" href="<?= Url::toRoute(['user/view', 'id' => $model->user_id]) ?>">
                    <?= CommonView::badge($model->user_id, 16) ?>
                    <?= $model->user_full_name ?>
                </a>
            </td>
        </tr>
        <tr>
            <td>
                <?= $model->getAttributeLabel('table') ?>
            </td>
            <td class="text-info">
                <?= $ref ? $ref::tableLabel() : '' ?>
                {<?= $model->table ?>}
            </td>
        </tr>
        <tr>
            <td>
                <?= $model->getAttributeLabel('reference_id') ?>
            </td>
            <td class="text-info">
                <?= $model->reference_id ?>
				<?=	yii\helpers\Html::a('历史记录', ['history', 'table' => $model->table, 'reference_id' => $model->reference_id]) ?>
            </td>
        </tr>
        <tr>
            <td>
                <?= $model->getAttributeLabel('action') ?>
            </td>
            <td class="text-info">
                <?= $model->getActionText() ?>
            </td>
        </tr>
        <tr>
            <td>
                <?= $model->getAttributeLabel('old') ?>
            </td>
            <td>
                <table class="table table-bordered table-condensed">
                    <?php
					$old = \yii\helpers\Json::decode($model->old);
					if($ref){
						foreach ($old as $k => $v){
                    ?>
                    <tr>
                        <td title="<?= $k ?>" class="text-info">
                            <?= $ref->getAttributeLabel($k) ?>
                        </td>
                        <td>
                            <?= $ref->textValue($k) ?>
                        </td>
                    </tr>
                    <?php
						}
					}else{
						foreach ($old as $k => $v){
                    ?>
                    <tr>
                        <td class="text-info">
                            <?= $k ?>
                        </td>
                        <td>
                            <?= $v ?>
                        </td>
                    </tr>
                    <?php
						}
					}
					?>
                </table>
            </td>
        </tr>
    </table>

</div>